### ISSUE TITLE
New UT failures on PVC 1550

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#667] opened 2024-07-31 03:03 UTC
### 🐛 Describe the bug

Details in https://github.com/mengfei25/torch-xpu-ops/actions/runs/10051995948/job/27838722875
2024-07-25T03:59:08.1105876Z =========================== short test summary info ============================
2024-07-25T03:59:08.1109596Z FAILED 

- [ ] test_modules_xpu.py::TestModuleXPU::test_cpu_gpu_parity_nn_ConvTranspose1d_xpu_complex32 - AssertionError: Tensor-likes are not close!

2024-07-25T03:59:08.1112233Z 
2024-07-25T03:59:08.1112650Z Mismatched elements: 7 / 50 (14.0%)
2024-07-25T03:59:08.1115013Z Greatest absolute difference: 0.006175994873046875 at index (0, 3, 3) (up to 1e-05 allowed)
2024-07-25T03:59:08.1118103Z Greatest relative difference: 0.0014667510986328125 at index (1, 1, 2) (up to 0.001 allowed)
2024-07-25T03:59:08.1119870Z 
2024-07-25T03:59:08.1120679Z To execute this test, run the following from the base repo dir:
2024-07-25T03:59:08.1124150Z     PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py -k TestModuleXPU.test_cpu_gpu_parity_nn_ConvTranspose1d_xpu_complex32
2024-07-25T03:59:08.1126478Z 
2024-07-25T03:59:08.1127594Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2024-07-25T03:59:08.1131740Z FAILED 

- [ ] test_modules_xpu.py::TestModuleXPU::test_cpu_gpu_parity_nn_ConvTranspose2d_xpu_complex32 - AssertionError: Tensor-likes are not close!

2024-07-25T03:59:08.1134298Z 
2024-07-25T03:59:08.1134727Z Mismatched elements: 49 / 300 (16.3%)
2024-07-25T03:59:08.1137126Z Greatest absolute difference: 0.00873565673828125 at index (0, 1, 2, 3) (up to 1e-05 allowed)
2024-07-25T03:59:08.1140065Z Greatest relative difference: 0.00299072265625 at index (1, 4, 1, 2) (up to 0.001 allowed)
2024-07-25T03:59:08.1141768Z 
2024-07-25T03:59:08.1142583Z To execute this test, run the following from the base repo dir:
2024-07-25T03:59:08.1146067Z     PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py -k TestModuleXPU.test_cpu_gpu_parity_nn_ConvTranspose2d_xpu_complex32
2024-07-25T03:59:08.1148372Z 
2024-07-25T03:59:08.1155465Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2024-07-25T03:59:08.1160094Z FAILED 

- [ ] test_modules_xpu.py::TestModuleXPU::test_non_contiguous_tensors_nn_LazyConvTranspose3d_xpu_float32 - AssertionError: Tensor-likes are not close!

2024-07-25T03:59:08.1162894Z 
2024-07-25T03:59:08.1163332Z Mismatched elements: 1 / 540 (0.2%)
2024-07-25T03:59:08.1165864Z Greatest absolute difference: 1.2636184692382812e-05 at index (2, 1, 1, 0, 2) (up to 1e-05 allowed)
2024-07-25T03:59:08.1169520Z Greatest relative difference: 5.799956124974415e-05 at index (2, 1, 1, 0, 2) (up to 1e-05 allowed)
2024-07-25T03:59:08.1171366Z 
2024-07-25T03:59:08.1171797Z The failure occurred for item [0]
2024-07-25T03:59:08.1172678Z 
2024-07-25T03:59:08.1177422Z To execute this test, run the following from the base repo dir:
2024-07-25T03:59:08.1181222Z     PYTORCH_TEST_WITH_SLOW=1 python test/test_modules.py -k TestModuleXPU.test_non_contiguous_tensors_nn_LazyConvTranspose3d_xpu_float32
2024-07-25T03:59:08.1183762Z 
2024-07-25T03:59:08.1184770Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2024-07-25T03:59:08.1187630Z = 3 failed, 2978 passed, 372 skipped, 229 deselected, 23 xfailed in 298.98s (0:04:58) =

### Versions

Device: PVC 1550
Driver: 803.61
Bundle: 0.5.3
PyTorch: bd12fbe65295fd59b73cfcf63eca32f30e5f15e5
Torch-xpu-ops: de744d9a92d5294041127235d1630466128eff1f

**Comment by mengfei25** [comment] 2024-07-31 06:09
test_non_contiguous_tensors_nn_LazyConvTranspose3d_xpu_float32 is known random issue
others are tracked in https://jira.devtools.intel.com/browse/GSD-9293

**Comment by riverliuintel** [comment] 2024-11-21 09:09
close this as root caused. driver issues has separate tickets to track.

**Closed by riverliuintel** 2024-11-21 09:09 UTC
Labels: bug
