### ISSUE TITLE
PI_ERROR_INVALID_QUEUE after copying device 0 tensor to device 1

### ISSUE THREAD

**Issue by daisyden** [intel/torch-xpu-ops#745] opened 2024-08-12 02:44 UTC
### 🐛 Describe the bug

```
import torch
a = torch.empty(3, device=torch.device('xpu:0'))
a.fill_(1.1)
b = a.to(device='xpu:1')
a.device
b.device
print(b.cpu())
**print(b)**
```
Report:
```
tensor([1.1000, 1.1000, 1.1000])
Traceback (most recent call last):
  File "/home/gta/daisyden/pytorch4/test/aa.py", line 8, in <module>
    print(b)
  File "/home/gta/miniforge3/envs/daisy_pytorch4/lib/python3.10/site-packages/torch/_tensor.py", line 464, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/home/gta/miniforge3/envs/daisy_pytorch4/lib/python3.10/site-packages/torch/_tensor_str.py", line 714, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/home/gta/miniforge3/envs/daisy_pytorch4/lib/python3.10/site-packages/torch/_tensor_str.py", line 631, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/home/gta/miniforge3/envs/daisy_pytorch4/lib/python3.10/site-packages/torch/_tensor_str.py", line 363, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/gta/miniforge3/envs/daisy_pytorch4/lib/python3.10/site-packages/torch/_tensor_str.py", line 152, in __init__
    nonzero_finite_vals = torch.masked_select(
RuntimeError: Native API failed. Native API returns: -36 (PI_ERROR_INVALID_QUEUE) -36 (PI_ERROR_INVALID_QUEUE)
```

### Versions

latest version

**Comment by fengyuan14** [comment] 2024-08-12 07:29
SYCL runtime issue.

As latest SYCL spec, we are recommended to use info::kernel_device_specific::work_group_size ([CMPLRLLVM-56688](https://jira.devtools.intel.com/browse/CMPLRLLVM-56688) [PVC] UT test_take.py::TestNNMethod::test_take - RuntimeError on hotfix_agama-ci-devel-775.19 - IT JIRA (Supports IC/ITS Data) (intel.com)) instead of info::device::max_work_group_size. But there is a new issue found. Cannot launch kernel successfully on PVC Tile 1 after querying info::kernel_device_specific::work_group_size. Got runtime error:

**Comment by daisyden** [comment] 2024-08-13 02:33
https://jira.devtools.intel.com/browse/CMPLRLLVM-60961

**Comment by daisyden** [comment] 2024-08-13 03:22
duplicated with https://github.com/intel/torch-xpu-ops/issues/622

**Comment by fengyuan14** [comment] 2024-08-16 05:47
The issue is common for all platform where there are devices more than one. The most important and most common case for us is client case, a client platform/desktop has an iGPU and an dGPU.

**Comment by fengyuan14** [comment] 2024-08-19 06:54
https://github.com/intel/llvm/issues/15127

**Comment by ddkalamk** [comment] 2024-09-13 06:10
@fengyuan14 can we please apply the workaround available to fix this problem?

i.e. change
https://github.com/intel/torch-xpu-ops/blob/main/src/comm/DeviceProperties.h#L19C3-L20C79
`auto kbundle =
      ::sycl::get_kernel_bundle<::sycl::bundle_state::executable>(ctx, {kid});`

to

`auto kbundle =
      ::sycl::get_kernel_bundle<::sycl::bundle_state::executable>(ctx, {dev}, {kid});`

**Comment by ddkalamk** [comment] 2024-09-13 06:23
@daisyden @fengyuan14 
Test results after applying fix:

```python
(pt_src) [ddkalamk@pcl-pvc01 pytorch]$ cat test2.py
import torch
print("PyTorch version: ", torch.__version__)
a = torch.empty(3, device=torch.device('xpu:0'))
a.fill_(1.1)
b = a.to(device='xpu:1')
a.device
b.device
print(b.cpu())
print(b)

(pt_src) [ddkalamk@pcl-pvc01 pytorch]$ python -u test2.py
PyTorch version:  2.5.0a0+git8693322
tensor([1.1000, 1.1000, 1.1000])
tensor([1.1000, 1.1000, 1.1000], device='xpu:1')

```

**Comment by fengyuan14** [comment] 2024-09-13 06:24
Hi, @ddkalamk.
We have got a PR for it on main branch. Recently, we are working on PT2.5 release. Will land the PR ASAP.
https://github.com/intel/torch-xpu-ops/pull/769

**Comment by ddkalamk** [comment] 2024-09-13 06:29
Sounds good, thanks.

**Comment by fengyuan14** [comment] 2024-10-15 05:09
The WA has been merged in main branch. https://github.com/intel/torch-xpu-ops/pull/769

**Closed by fengyuan14** 2024-10-15 05:09 UTC
Labels: ut_triage, client
