### ISSUE TITLE
[PT2.6][Client GPU Windows] Windows build log is too big to open

### ISSUE THREAD

**Issue by riverliuintel** [intel/torch-xpu-ops#999] opened 2024-10-22 11:13 UTC
### 🚀 The feature, motivation and pitch

Windows build log size is too big to open in web, which impact issue triage in CI. Need to enhance windows build log and clean the warning message in Windows.

**Comment by min-jean-cho** [comment] 2024-10-25 21:32
The excessive verbosity was caused by SYCL compiler `/clang:-MD` used with `-fsycl-host-compiler=cl.exe`, which invoked `-E`. `-E` emits the preprocessed source code to stdout, causing the excessive verbosity.
The issue has been resolved with SYCL compiler of oneAPI 2025.

**Closed** 2024-11-19 07:18 UTC
Labels: Windows
