### ISSUE TITLE
Sigmoid op didn't be supported with complex32 which didn't align with CUDA behavior.

### ISSUE THREAD

**Issue by PenghuiCheng** [intel/torch-xpu-ops#435] opened 2024-06-19 11:56 UTC
### 🐛 Describe the bug

log:
RuntimeError: "sigmoid_xpu" not implemented for 'ComplexHalf'
cases:
TestCommonXPU.test_complex_half_reference_testing_sigmoid_xpu_complex32
TestCommonXPU.test_complex_half_reference_testing_sigmoid_xpu_complex32
TestCommonXPU.test_dtypes_sigmoid_xpu
 TestCommonXPU.test_python_ref__refs_sigmoid_xpu_complex32
 TestCommonXPU.test_python_ref_errors__refs_where_xpu
 TestCommonXPU.test_python_ref_executor__refs_sigmoid_executor_aten_xpu_complex32
TestCommonXPU.test_python_ref_torch_fallback__refs_sigmoid_xpu_complex32

### Versions

latest version

**Comment by fengyuan14** [comment] 2024-06-22 06:01
https://github.com/intel/torch-xpu-ops/pull/429

**Comment by fengyuan14** [comment] 2024-06-22 06:01
Please verify, the issue is fixed. And cases are retrieved.

**Comment by chuanqi129** [comment] 2024-07-11 09:22
@PenghuiCheng please double check it. If it has been fixed, please close this issue

**Closed** 2024-07-18 01:41 UTC
Labels: feature, ut_triage

**Comment by chuanqi129** [comment] 2024-07-18 01:42
Confirmed with @fengyuan14, we can close this issue
