### ISSUE TITLE
UT got scratch page issue with rolling driver

### ISSUE THREAD

**Issue by mengfei25** [intel/torch-xpu-ops#598] opened 2024-07-16 09:01 UTC
### 🐛 Describe the bug

TestCommonXPU::test_out_bincount_xpu_int64
2024-07-11T08:48:47.7389771Z FATAL: Unexpected page fault from GPU at 0x56443f92d000, ctx_id: 1 (CCS) type: 0 (NotPresent), level: 3 (PML4), access: 1 (Write), banned: 1, aborting.

### Versions

Driver: 914.30 with envs: export NEOReadDebugKeys=1, export DisableScratchPages=1
Bundle: 0.5.1
torch-xpu-ops: https://github.com/intel/torch-xpu-ops/commit/01d4375a5bf6766fbdf0be2c1a3630105fc8b6a9
pytorch: 2f21c45513b13f238a18afaab2f98456399d76a3

**Comment by Stonepia** [comment] 2024-07-23 02:56
The issue is fixed in the latest Pytorch and torch-xpu-ops bundle. Verified using the test machine as well as the following env:

```
PyTorch: 28b0ad4f4616497e9e297d3970992aad1d3cba44  (July. 23)
torch-xpu-ops: 5f4970b4aa6ef47a695baf01d5533d106fc69b82 (July. 23)

Driver (level-zero): 1.3.29735.27-914~22.04  
```

```Bash
$ PYTORCH_TEST_WITH_SLOW=1 pytest -v test_ops_xpu.py -k test_out_bincount_xpu_int64

collected 14706 items / 14705 deselected / 1 selected
 
test_ops_xpu.py::TestCommonXPU::test_out_bincount_xpu_int64 PASSED                                                                                                                                                                                                                 [100%]
```

In view of that, I will close this issue.

**Closed by Stonepia** 2024-07-23 02:56 UTC
Labels: bug
